### PR TITLE
abstract out COL_BYTES, fix loop ranges

### LINKED ISSUE #1: scrolling code is still off
two things from this screenshot: 

2016-09-25-094023_783x467_scrot
1. see those `fff`s in the upper right? And how they have space to the left? This means that we're not scrolling the full screen.
2. the colors are inverted on the final line when it's cleared.

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #1 
- abstract out const `COL_BYTES` (`COLS * 2`)
- update scroll loops to go through `0..COL_BYTES` not `0..COLS`

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
please test? @steveklabnik

**Comment by steveklabnik** [comment]
Almost! It's scrolling but the colors on the new line are wrong: 
2016-09-25-103016_758x501_scrot

**Comment by steveklabnik** [comment]
Now it's setting the background, but not the letters:

2016-09-25-104704_678x403_scrot

**Comment by steveklabnik** [comment]
:confetti_ball:

**Pull request merged**
